language: "en"

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CRFEntityExtractor" # Added for better entity extraction
  - name: "DIETClassifier"
    epochs: 100
    entity_recognition: True # Ensure entity recognition is enabled
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
  - name: "FallbackClassifier" # Optional: To handle unrecognized intents
    threshold: 0.3

policies:
  - name: "MemoizationPolicy"
  - name: "RulePolicy"
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100

assistant_id: 20241027-124906-matte-stack
